name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-dev:
    name: Terraform dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.1"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: infra/envs/dev
        run: terraform init -backend=false -input=false

      - name: Terraform Validate
        working-directory: infra/envs/dev
        run: terraform validate -no-color

  terraform-prod:
    name: Terraform prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.1"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: infra/envs/prod
        run: terraform init -backend=false -input=false

      - name: Terraform Validate
        working-directory: infra/envs/prod
        run: terraform validate -no-color
